
spring:
  application:
    name: edupay


    #profiles:
    # include: rds

  datasource:
    url: jdbc:mysql://database-2.cf48wq8e4ow8.ap-northeast-2.rds.amazonaws.com:3306/edupay
    username: admin
    password: edupay123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
#      naming:
        #strategy: org.hibernate.cfg.ImprovedNamingStrategy
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
#        enable_lazy_load_no_trans: true

#  data:
#    redis:
#      host: localhost
#      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_MAIL_USERNAME}
    password: ${GOOGLE_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secretKey: 034509324804235843098432144543676546435



email:
  password-reset:
    url: http://localhost:8080/users/check-reset-password

imp:
  code: imp27833651
  api:
    key: 5460384277175472
    secret_key: bOZm2BopeFJQ3SBTSE5m70CWqA97Q1SFIBWcHRL1TGuRA8kDmcEFIfLPjHjMQUm8Qw7ZlfG7VcMBKUOr