
spring:
  application:
    name: edupay


    #profiles:
    # include: rds

  datasource:
    url: jdbc:mysql://database-2.cf48wq8e4ow8.ap-northeast-2.rds.amazonaws.com:3306/edupay
    username: admin
    password: edupay123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    generate-ddgl: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: 10s

  mail:
    host: smtp.gmail.com
    port: 587
    username: js020315@gmail.com
    password: pfyg fpmx gric wfxg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secretKey: 034509324804235843098432144543676546435

springdoc:
  version: v1.0.0
  packages-to-scan: com.eliceteam8.edupay
  swagger-ui:
    path: /api-edupay
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-edupay/json
    groups:
      enabled: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

email:
  password-reset:
    url: http://localhost:8080/users/check-reset-password

imp:
  code: imp25436403
  api:
    key: 5143242737360173
    secret_key: 62uhL0GDffjlifz0luL9Ekzp2HUGWmaNneqh57BAatTyC8ejRI9u5zqHzq4txaREeM39Zgj5PtgHNd7U